name: New release created
on:
  release:
    types:
      - released

jobs:
  update-homebrew:
    name: Update homebrew formula
    runs-on: ubuntu-latest
    steps:
    - uses: mislav/bump-homebrew-formula-action@v1
      with: { formula-name: jenv }
      env:
        COMMITTER_TOKEN: ${{ secrets.BREW_TOKEN }}
